 const LOAN_STATUS=0;
const FINE_STATUS=0;
const INITIAL_AMAOUNT_STATUS=0;
const LOAN_AMOUNT=0;
const FINE_AMOUNT=0;

module.exports = {
    LOAN_STATUS,
    FINE_STATUS,
    INITIAL_AMAOUNT_STATUS,
    LOAN_AMOUNT,
    FINE_AMOUNT
}
